apiVersion: v1
kind: Service
metadata:
  name: {{ include "blindbucket.fullname" . }}
  labels:
    {{- include "blindbucket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "blindbucket.selectorLabels" . | nindent 4 }}
  ports:
    - { name: s3, port: {{ .Values.service.port }}, targetPort: s3, protocol: TCP }
    - { name: admin, port: {{ .Values.service.adminPort }}, targetPort: admin, protocol: TCP }
